openapi: 3.0.0
info:
  title: CarBorbala
  description: CarBorbala web app API
  version: 0.1.9

servers:
  - url: http://localhost:5000/api
    description: production server
  - url: http://localhost:5000/api
    description: local server
paths:
  /cars:
    get:
      tags:
        - Cars
      responses:
        "200":
          description: cars returned successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                model:
                  type: string
                type:
                  type: string
                price:
                  type: string
                img:
                  type: string
  /register:
    get:
      tags:
        - Auth
      requestBody:
        description: user registration request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: user regisred successfully
